/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { Contract, ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import { ContractEvent, Callback, TransactionObject, BlockType } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class AggregatorV3Interface extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  clone(): AggregatorV3Interface;
  methods: {
    decimals(): TransactionObject<string>;

    description(): TransactionObject<string>;

    getRoundData(
      _roundId: number | string
    ): TransactionObject<{
      roundId: string;
      answer: string;
      startedAt: string;
      updatedAt: string;
      answeredInRound: string;
      0: string;
      1: string;
      2: string;
      3: string;
      4: string;
    }>;

    latestRoundData(): TransactionObject<{
      roundId: string;
      answer: string;
      startedAt: string;
      updatedAt: string;
      answeredInRound: string;
      0: string;
      1: string;
      2: string;
      3: string;
      4: string;
    }>;

    version(): TransactionObject<string>;
  };
  events: {
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
