/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { Contract, ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import { ContractEvent, Callback, TransactionObject, BlockType } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class AggregatorInterface extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  clone(): AggregatorInterface;
  methods: {
    getAnswer(roundId: number | string): TransactionObject<string>;

    getTimestamp(roundId: number | string): TransactionObject<string>;

    latestAnswer(): TransactionObject<string>;

    latestRound(): TransactionObject<string>;

    latestTimestamp(): TransactionObject<string>;
  };
  events: {
    AnswerUpdated: ContractEvent<{
      current: string;
      roundId: string;
      timestamp: string;
      0: string;
      1: string;
      2: string;
    }>;
    NewRound: ContractEvent<{
      roundId: string;
      startedBy: string;
      startedAt: string;
      0: string;
      1: string;
      2: string;
    }>;
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
