/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { Contract, ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import { ContractEvent, Callback, TransactionObject, BlockType } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class AnimationLib extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  clone(): AnimationLib;
  methods: {
    _generateAnimation(
      box: {
        randomness: number | string;
        hue: number | string;
        saturation: number | string;
        lightness: number | string;
        shapes: number | string;
        hatching: number | string;
        widthMin: number | string;
        widthMax: number | string;
        heightMin: number | string;
        heightMax: number | string;
        spread: number | string;
        grid: number | string;
        mirroring: number | string;
        bkg: number | string;
        duration: number | string;
        options: number | string;
      },
      animation: number | string,
      shape: {
        position: (number | string)[];
        size: (number | string)[];
        color: {
          hue: number | string;
          saturation: number | string;
          lightness: number | string;
        };
      },
      shapeIndex: number | string
    ): TransactionObject<string>;
  };
  events: {
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
