/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { Contract, ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import { ContractEvent, Callback, TransactionObject, BlockType } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class ChainlinkRequestInterface extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  clone(): ChainlinkRequestInterface;
  methods: {
    cancelOracleRequest(
      requestId: string | number[],
      payment: number | string,
      callbackFunctionId: string | number[],
      expiration: number | string
    ): TransactionObject<void>;

    oracleRequest(
      sender: string,
      requestPrice: number | string,
      serviceAgreementID: string | number[],
      callbackAddress: string,
      callbackFunctionId: string | number[],
      nonce: number | string,
      dataVersion: number | string,
      data: string | number[]
    ): TransactionObject<void>;
  };
  events: {
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
