/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { Contract, ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import { ContractEvent, Callback, TransactionObject, BlockType } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class OracleInterface extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  clone(): OracleInterface;
  methods: {
    fulfillOracleRequest(
      requestId: string | number[],
      payment: number | string,
      callbackAddress: string,
      callbackFunctionId: string | number[],
      expiration: number | string,
      data: string | number[]
    ): TransactionObject<boolean>;

    getAuthorizationStatus(node: string): TransactionObject<boolean>;

    setFulfillmentPermission(
      node: string,
      allowed: boolean
    ): TransactionObject<void>;

    withdraw(
      recipient: string,
      amount: number | string
    ): TransactionObject<void>;

    withdrawable(): TransactionObject<string>;
  };
  events: {
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
