/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { Contract, ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import { ContractEvent, Callback, TransactionObject, BlockType } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class PaymentSplitter extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  clone(): PaymentSplitter;
  methods: {
    payee(index: number | string): TransactionObject<string>;

    release(account: string): TransactionObject<void>;

    released(account: string): TransactionObject<string>;

    shares(account: string): TransactionObject<string>;

    totalReleased(): TransactionObject<string>;

    totalShares(): TransactionObject<string>;
  };
  events: {
    PayeeAdded: ContractEvent<{
      account: string;
      shares: string;
      0: string;
      1: string;
    }>;
    PaymentReceived: ContractEvent<{
      from: string;
      amount: string;
      0: string;
      1: string;
    }>;
    PaymentReleased: ContractEvent<{
      to: string;
      amount: string;
      0: string;
      1: string;
    }>;
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
