/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { Contract, ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import { ContractEvent, Callback, TransactionObject, BlockType } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class TinyBoxesPricing extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  clone(): TinyBoxesPricing;
  methods: {
    linkPremium(): TransactionObject<string>;

    linkPriceAt(_id: number | string): TransactionObject<string>;

    priceAt(_id: number | string): TransactionObject<string>;

    priceIncrease(): TransactionObject<string>;

    startPrice(): TransactionObject<string>;
  };
  events: {
    ChainlinkCancelled: ContractEvent<string>;
    ChainlinkFulfilled: ContractEvent<string>;
    ChainlinkRequested: ContractEvent<string>;
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
