/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { Contract, ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import { ContractEvent, Callback, TransactionObject, BlockType } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class TinyBoxes extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  clone(): TinyBoxes;
  methods: {
    ANIMATION_COUNT(): TransactionObject<string>;

    ARTIST_PRINTS(): TransactionObject<string>;

    TOKEN_LIMIT(): TransactionObject<string>;

    animator(): TransactionObject<string>;

    approve(to: string, tokenId: number | string): TransactionObject<void>;

    balanceOf(owner: string): TransactionObject<string>;

    baseURI(): TransactionObject<string>;

    createBox(
      _seed: string,
      counts: (number | string)[],
      dials: (number | string)[],
      mirrors: boolean[]
    ): TransactionObject<void>;

    creator(): TransactionObject<string>;

    currentPrice(): TransactionObject<string>;

    fulfillRandomness(
      requestId: string | number[],
      randomness: number | string
    ): TransactionObject<void>;

    getApproved(tokenId: number | string): TransactionObject<string>;

    isApprovedForAll(
      owner: string,
      operator: string
    ): TransactionObject<boolean>;

    name(): TransactionObject<string>;

    nonces(arg0: string | number[]): TransactionObject<string>;

    ownerOf(tokenId: number | string): TransactionObject<string>;

    perpetualRenderer(
      _id: number | string,
      box: {
        seed: number | string;
        randomness: number | string;
        animation: number | string;
        shapes: number | string;
        colors: number | string;
        hatching: number | string;
        scale: number | string;
        mirrorPositions: (number | string)[];
        size: (number | string)[];
        spacing: (number | string)[];
        mirrors: boolean[];
      },
      frame: number | string
    ): TransactionObject<string>;

    priceAt(_id: number | string): TransactionObject<string>;

    requestRandomness(
      _keyHash: string | number[],
      _fee: number | string,
      _seed: number | string
    ): TransactionObject<string>;

    safeTransferFrom(
      from: string,
      to: string,
      tokenId: number | string
    ): TransactionObject<void>;

    setApprovalForAll(
      operator: string,
      approved: boolean
    ): TransactionObject<void>;

    supportsInterface(
      interfaceId: string | number[]
    ): TransactionObject<boolean>;

    symbol(): TransactionObject<string>;

    tokenAnimation(_id: number | string): TransactionObject<string>;

    tokenArt(_id: number | string): TransactionObject<string>;

    tokenByIndex(index: number | string): TransactionObject<string>;

    tokenData(
      _id: number | string
    ): TransactionObject<{
      seed: string;
      animation: string;
      colors: string;
      shapes: string;
      hatching: string;
      size: string[];
      spacing: string[];
      mirrorPositions: string[];
      mirrors: boolean[];
      scale: string;
      0: string;
      1: string;
      2: string;
      3: string;
      4: string;
      5: string[];
      6: string[];
      7: string[];
      8: boolean[];
      9: string;
    }>;

    tokenFrame(
      _id: number | string,
      _frame: number | string
    ): TransactionObject<string>;

    tokenOfOwnerByIndex(
      owner: string,
      index: number | string
    ): TransactionObject<string>;

    tokenPreview(
      _id: number | string,
      _seed: string,
      counts: (number | string)[],
      dials: (number | string)[],
      mirrors: boolean[]
    ): TransactionObject<string>;

    tokenSeed(_id: number | string): TransactionObject<string>;

    tokenURI(tokenId: number | string): TransactionObject<string>;

    totalSupply(): TransactionObject<string>;

    transferFrom(
      from: string,
      to: string,
      tokenId: number | string
    ): TransactionObject<void>;

    updateURI(_id: number | string, _uri: string): TransactionObject<void>;
  };
  events: {
    Approval: ContractEvent<{
      owner: string;
      approved: string;
      tokenId: string;
      0: string;
      1: string;
      2: string;
    }>;
    ApprovalForAll: ContractEvent<{
      owner: string;
      operator: string;
      approved: boolean;
      0: string;
      1: string;
      2: boolean;
    }>;
    Transfer: ContractEvent<{
      from: string;
      to: string;
      tokenId: string;
      0: string;
      1: string;
      2: string;
    }>;
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
